# Generated by Django 5.0.3 on 2024-03-13 03:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achronym', models.CharField(help_text='Acronimo del banco', max_length=10, null=True, unique=True)),
                ('code', models.CharField(db_column='code', help_text='Codigo del banco', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Nombre del banco', max_length=100)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'banks',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Descripción corta del departamento', null=True)),
                ('email', models.CharField(help_text='email de cada departamento', max_length=60)),
                ('name', models.CharField(help_text='nombre', max_length=50)),
                ('rif', models.CharField(help_text='nombre', max_length=50)),
                ('start_date_work', models.DateField(help_text='fecha en la que empezo adquiri el servicio la empresa')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Statu',
                'verbose_name_plural': 'Status',
                'db_table': 'status',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True)),
                ('currency', models.CharField(help_text='Divisa/Moneda de la forma de pago', max_length=100)),
                ('name', models.CharField(help_text='Forma de pago', max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(help_text='Estado de Factura', on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
            options={
                'verbose_name': 'Payment Form',
                'verbose_name_plural': 'Payment Forms',
                'db_table': 'payment_methods',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentsCompany',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=50)),
                ('date', models.DateTimeField(help_text='Fecha en la que se registro el pago')),
                ('description', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(help_text='Titular enviante de transacción', max_length=300, null=True)),
                ('reference', models.TextField(help_text='referencia de pagomovil/transferencia', null=True)),
                ('sender', models.CharField(help_text='nombre de la cuenta del zelle', max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='Compañia que esta adquiriendo el servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.companies')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('receiving_bank', models.ForeignKey(blank=True, db_constraint=False, help_text='Banco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.banks')),
                ('sender_bank', models.ForeignKey(blank=True, db_constraint=False, help_text='Banco', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.banks')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(blank=True, db_constraint=False, help_text='Método de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.paymentmethods')),
            ],
            options={
                'verbose_name': 'historical payments company',
                'verbose_name_plural': 'historical payments companys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentsCompany',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del pago', max_digits=50)),
                ('date', models.DateTimeField(help_text='Fecha en la que se registro el pago')),
                ('description', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(help_text='Titular enviante de transacción', max_length=300, null=True)),
                ('reference', models.TextField(help_text='referencia de pagomovil/transferencia', null=True)),
                ('sender', models.CharField(help_text='nombre de la cuenta del zelle', max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
                ('company', models.ForeignKey(help_text='Compañia que esta adquiriendo el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='payments_company', to='app.companies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(help_text='Método de pago', on_delete=django.db.models.deletion.CASCADE, related_name='payment_company', to='app.paymentmethods')),
                ('receiving_bank', models.ForeignKey(help_text='Banco', on_delete=django.db.models.deletion.CASCADE, related_name='receiving_payment_company', to='app.banks')),
                ('sender_bank', models.ForeignKey(help_text='Banco', on_delete=django.db.models.deletion.CASCADE, related_name='sender_payment_company', to='app.banks')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_company',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMethods',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('currency', models.CharField(help_text='Divisa/Moneda de la forma de pago', max_length=100)),
                ('name', models.CharField(help_text='Forma de pago', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, help_text='Estado de Factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.status')),
            ],
            options={
                'verbose_name': 'historical Payment Form',
                'verbose_name_plural': 'historical Payment Forms',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
