# Generated by Django 5.0.3 on 2024-03-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_receiving_bank_historicalpaymentscompany_bank_destiny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.ForeignKey(default=1, help_text='Tienda en la que se encuentra el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.companies'),
            preserve_default=False,
        ),
    ]
