# Generated by Django 5.0.3 on 2024-03-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='company',
            field=models.ForeignKey(help_text='Tienda en la que se encuentra el usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.companies'),
        ),
    ]
