# Generated by Django 5.0.3 on 2024-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentscompany',
            options={'ordering': ('-id',), 'permissions': (('validate_paymentscompany', 'Can validate Payments Company'),)},
        ),
    ]
