# Generated by Django 5.0.3 on 2024-03-29 04:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_paymentscompany_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('type', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'options',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='historicalpaymentmethods',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical payment methods', 'verbose_name_plural': 'historical payment methodss'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='companies',
            name='status',
            field=models.ForeignKey(default=1, help_text='Estado de la compañia', on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentmethods',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='Estado del metodo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.status'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='status',
            field=models.ForeignKey(default=1, help_text='Estado del metodo de pago', on_delete=django.db.models.deletion.CASCADE, to='app.status'),
        ),
        migrations.CreateModel(
            name='HistoricalPaymentMethodsCompanies',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='compañia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.companies')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, db_constraint=False, help_text='metodo de pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.paymentmethods')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=1, help_text='status del metodo de pago de la compalia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.status')),
            ],
            options={
                'verbose_name': 'historical payment methods companies',
                'verbose_name_plural': 'historical payment methods companiess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCompaniesOptions',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='compañia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.companies')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, db_constraint=False, help_text='opcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.options')),
            ],
            options={
                'verbose_name': 'historical companies options',
                'verbose_name_plural': 'historical companies optionss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CompaniesOptions',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('company', models.ForeignKey(help_text='compañia', on_delete=django.db.models.deletion.CASCADE, related_name='company_options', to='app.companies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(help_text='opcion', on_delete=django.db.models.deletion.CASCADE, related_name='option_companies', to='app.options')),
            ],
            options={
                'db_table': 'companies_options',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodsCompanies',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('company', models.ForeignKey(help_text='compañia', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods_companies', to='app.companies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(help_text='metodo de pago', on_delete=django.db.models.deletion.CASCADE, related_name='companies_payment_methods', to='app.paymentmethods')),
                ('status', models.ForeignKey(default=1, help_text='status del metodo de pago de la compalia', on_delete=django.db.models.deletion.CASCADE, to='app.status')),
            ],
            options={
                'db_table': 'payment_methods_companies',
                'ordering': ('-id',),
            },
        ),
    ]
