# Generated by Django 5.0.3 on 2024-05-17 18:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_users_company_alter_users_email_users_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='company',
        ),
        migrations.AlterField(
            model_name='companies',
            name='start_date_work',
            field=models.DateField(help_text='fecha en la que empezó adquirí el servicio la empresa'),
        ),
        migrations.AlterField(
            model_name='historicalpaymentscompany',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Compañía que esta adquiriendo el servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.companies'),
        ),
        migrations.AlterField(
            model_name='paymentscompany',
            name='company',
            field=models.ForeignKey(help_text='Compañía que esta adquiriendo el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='payments_company', to='app.companies'),
        ),
        migrations.CreateModel(
            name='HistoricalUserCompanies',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_index=True, editable=False, help_text='ID único para la instancia del modelo.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Fecha de actualización del objeto', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='compañia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.companies')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='Compañía del usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user companies',
                'verbose_name_plural': 'historical user companiess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserCompanies',
            fields=[
                ('id', models.BigAutoField(editable=False, help_text='ID único para la instancia del modelo.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del objeto', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de actualización del objeto', null=True)),
                ('company', models.ForeignKey(help_text='compañia', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='app.companies')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Compañía del usuario', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_companies',
                'ordering': ('-id',),
            },
        ),
    ]
