# Generated by Django 5.0.3 on 2024-05-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_users_company_alter_companies_start_date_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusercompanies',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalusercompanies',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='usercompanies',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='usercompanies',
            name='updated_by',
        ),
    ]
