# Generated by Django 5.0.3 on 2024-05-17 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_historicalusercompanies_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusercompanies',
            name='company_status_id',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Status de la compañía', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.status'),
        ),
        migrations.AddField(
            model_name='usercompanies',
            name='company_status_id',
            field=models.ForeignKey(default=1, help_text='Status de la compañía', on_delete=django.db.models.deletion.CASCADE, related_name='status', to='app.status'),
            preserve_default=False,
        ),
    ]
